In [1]:
from sklearn.model_selection import cross_val_predict, KFold
import sklearn
import numpy as np
import os
import sys

In [5]:
# define a list of datasets
datasets = [
"BEARING_Univar",
"PHM2022_Multivar",
"PHM2022_Univar_PIN",
"PHM2022_Univar_PO",
"PHM2022_Univar_PDIN",
"ETCHING_Multivar",
"MFPT_48KHZ_Univar",
"MFPT_96KHZ_Univar",
"PADERBORN_64KHZ_Univar",
"PADERBORN_4KHZ_Univar",
"PADERBORN_64KHZ_Multivar",
"PADERBORN_4KHZ_Multivar",
"Hydraulic_systems_10HZ_Multivar",
"Hydraulic_systems_100HZ_Multivar",
"Gas_sensors_home_activity",
"Control_charts",
"CWRU_12k_DE_univar",
"CWRU_12k_DE_multivar",
"CWRU_12k_FE_univar",
"CWRU_12k_FE_multivar",
"CWRU_48k_DE_univar",
"CWRU_48k_DE_multivar"
]
print("We have {} Datasets for evaluation".format(len(datasets)))

#datasets = ["PHM2022_Multivar", "PHM2022_Univar_PDIN"]

datasets_path = "../datasets"

for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    print(Dataset.shape)
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")


We have 22 Datasets for evaluation
(2560, 8192, 1)
(53785, 749, 3)
(53785, 749, 1)
(53785, 749, 1)
(53785, 749, 1)
(128, 112, 18)
(1898, 2000, 1)
(1898, 4000, 1)
(192477, 3000, 1)
(185520, 200, 1)
(192477, 3000, 3)
(185520, 200, 5)
(2205, 600, 17)
(2205, 6000, 7)
(99, 15393, 10)
(600, 60, 1)
(7200, 1000, 1)
(6240, 1000, 3)
(5400, 1000, 1)
(5400, 1000, 3)
(10681, 2000, 1)
(10681, 2000, 2)


In [ ]:
# change this directory for your machine
root_dir = './'

algorirhms_path = "./classifiers"

from classifiers import LR_module

# define the number of folds
n_folds = 5

# perform cross-validation for each dataset and algorithm combination
for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")

    # Create a folder for results
    results_path = root_dir + "Results/" + Dataset_name
    if os.path.exists(results_path):
        pass
    else:
        try:
            os.makedirs(results_path)
        except:
            # in case another machine created the path meanwhile !:(
            pass



    #Run The Logistic Regression (LR) module
    LR_module.LR(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, C=10)







 The dataset shape is:(2560, 8192, 1)

 The number of data samples (N) is:2560

 The number of TS length (T) is:8192

 The number of TS dimention (M) is:1
0.177734375
0.17397789519420764
[[19 13  4 11  7  8  4  5]
 [11 12  7  7  7  7  3  7]
 [ 5 13 14  7  4  4  3  5]
 [10 12  9 11  5  5  2  1]
 [ 8 13  9 10 15  3  0 12]
 [13 14  5 11  8  9  4  5]
 [ 7 14  7 11 11  6  5  7]
 [10 10  6 13  7  5  6  6]]
              precision    recall  f1-score   support

         1.0       0.23      0.27      0.25        71
         2.0       0.12      0.20      0.15        61
         3.0       0.23      0.25      0.24        55
         4.0       0.14      0.20      0.16        55
         5.0       0.23      0.21      0.22        70
         6.0       0.19      0.13      0.16        69
         7.0       0.19      0.07      0.11        68
         8.0       0.12      0.10      0.11        63

    accuracy                           0.18       512
   macro avg       0.18      0.18      0.17       512