In [1]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import cross_val_predict, KFold

# LR model 
import sklearn
import numpy as np
import os
import sys


In [2]:
# define a list of datasets
datasets = ["PHM2022_Multivar", "PHM2022_Univar_PDIN"]
datasets_path = "./datasets"

for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    print(Dataset.shape)
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")


(53785, 749, 3)
(53785, 749, 1)


In [3]:
# change this directory for your machine
root_dir = './'


#add the classifier path to the sys
sys.path.append("./classifiers/")

# define a list of datasets
datasets = ["PHM2022_Multivar", "PHM2022_Univar_PDIN"]
datasets_path = "./datasets"

# define a list of algorithms
#algorithms = [LR_module]
algorirhms_path = "./classifiers"

sys.path.append("./classifiers")
from classifiers import LR_module
from classifiers import SVM_module
from classifiers import RF_module

# define the number of folds
n_folds = 5

# perform cross-validation for each dataset and algorithm combination
for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")

    # Create a folder for results
    results_path = root_dir + "Results/" + Dataset_name
    if os.path.exists(results_path):
        pass
    else:
        try:
            os.makedirs(results_path)
        except:
            # in case another machine created the path meanwhile !:(
            pass


    #Run The Logistic Regression (LR) module
    LR_module.LR(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, C=10)

    #Run The Support Vector Machine (SVM) Module
    SVM_module.SVM(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, C=1)

    #Run The Random Forest (RF) Module
    RF_module.RF(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, n_trees=500)


    




 The dataset shape is:(53785, 749, 3)

 The number of data samples (N) is:53785

 The number of TS length (T) is:749

 The number of TS dimention (M) is:3
LR is not capable of doing classification on MTS. so it will be done on only the first dimension


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9263735242167891
0.9259665397860946
[[3732   14   20   25    7   23   17    9   23   21   11   15]
 [  53  548    0    9    0   34    0    4    2    1    6   18]
 [  35    0  657    0    0    0    0    0    0    0    0    0]
 [  43   11    0  547    0    4    0    2    1    0   14    8]
 [   6    0    0    0  624    0    0    2    1    0    0    2]
 [   8   17    0    3    0  560    0    0    0    0    0    9]
 [  16    0    0    1    0    0  539    1    0    0    0    0]
 [  14    0    0    3    0    0    0  586   17    1    0    0]
 [  26    1    0    1    0    3    0   16  517    1    3    6]
 [  11    0    0    1    2    4    1    0    0  625    3    1]
 [  48   16    0    6    0    1    0    0    0    0  451   26]
 [  38   14    0    5    0    5    0    0    1    1   20  579]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      3917
           1       0.88      0.81      0.85       675
           2       0.97      0.95      0.9

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9236776052802826
0.9236305546299287
[[3561   20   20   34    6   33   19   14   27   14   30   28]
 [  38  556    0    3    0   19    0    3    0    0   10   11]
 [  20    0  673    0    1    0    0    0    0    1    0    0]
 [  39    9    0  552    1    0    0    2    2    1   12   11]
 [   5    0    0    0  616    0    0    1    0    1    0    0]
 [   4   32    0    5    0  573    0    0    0    1    0   11]
 [  13    0    0    0    0    0  612    0    0    1    0    0]
 [  18    0    0    5    0    0    0  603   15    0    0    0]
 [  45    0    0    1    0    0    0   18  571    2    3    3]
 [  21    2    0    3    0    1    0    5    1  583    6    2]
 [  43    5    0    4    0    3    0    0    2    0  471   27]
 [  42   14    0    7    0    4    0    0    1    0   16  565]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93      3806
           1       0.87      0.87      0.87       640
           2       0.97      0.97      0.9

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9257227851631495
0.9255070112781602
[[3735   15   27   27   11   28   20   20   25   19   22   20]
 [  32  520    0    7    0   20    0    3    1    0    7   14]
 [  21    0  671    0    1    0    0    0    0    0    0    0]
 [  48    9    0  513    0    0    0    4    3    0   13    9]
 [   5    0    0    0  614    0    0    2    0    0    0    1]
 [  10   27    0    8    0  578    0    0    1    1    4   14]
 [  14    0    0    0    0    0  623    0    0    2    0    0]
 [  16    0    0    0    0    0    0  626   14    0    1    0]
 [  30    2    0    1    0    0    0   22  543    2    2    5]
 [  23    1    0    1    0    0    0    0    0  588    0    2]
 [  38   14    0    4    0    1    0    1    2    1  422   26]
 [  45   10    0    3    0    3    0    0    2    0   12  525]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.94      3969
           1       0.87      0.86      0.87       604
           2       0.96      0.97      0.9

/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.924886120665613
0.9246086934805884
[[3631   17   33   17    7   23   18   13   23    6   20   34]
 [  42  574    0    8    0   25    0    5    2    0    6   13]
 [  24    0  642    0    0    0    0    0    0    0    0    0]
 [  46   14    0  535    1    1    0    2    0    0   11   12]
 [   4    0    0    0  597    0    0    1    0    1    0    0]
 [   7   32    0    7    1  540    0    0    3    3    2    9]
 [  14    0    0    0    1    0  641    0    0    1    0    0]
 [  23    0    0    0    0    0    0  610    6    0    1    0]
 [  30    0    0    4    0    0    0   18  550    2    2    6]
 [  22    0    0    1    0    1    1    2    0  605    1    0]
 [  51   14    0    4    0    1    0    2    2    0  458   25]
 [  46    6    0    3    0    3    0    3    3    1   15  566]]
              precision    recall  f1-score   support

           0       0.92      0.95      0.93      3842
           1       0.87      0.85      0.86       675
           2       0.95      0.96      0.96