In [1]:
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.model_selection import cross_val_predict, KFold

# LR model 
import sklearn
import numpy as np
import os
import sys
from joblib import parallel_backend



In [2]:
# define a list of datasets
datasets = ["PHM2022_Multivar", "PHM2022_Univar_PDIN"]
datasets_path = "../datasets"

for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    print(Dataset.shape)
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")


(53785, 749, 3)
(53785, 749, 1)


In [14]:
# change this directory for your machine
root_dir = './'


#add the classifier path to the sys
#sys.path.append("./classifiers/")

# define a list of datasets
#datasets = ["PHM2022_Multivar", "PHM2022_Univar_PDIN"]
datasets_path = "../datasets"

# define a list of algorithms
#algorithms = [LR_module]
algorirhms_path = "./classifiers"

from classifiers import LR_module
from classifiers import SVM_module
from classifiers import RF_module
from classifiers import NB_module

# define the number of folds
n_folds = 5

# perform cross-validation for each dataset and algorithm combination
for dataset in datasets:
    Dataset_name = dataset + "_Dataset"
    Dataset = np.load(datasets_path + "/" + Dataset_name + ".npy")
    

    Labels_name = dataset + "_Labels"
    Labels = np.load(datasets_path + "/"  + Labels_name + ".npy")

    # Create a folder for results
    results_path = root_dir + "Results/" + Dataset_name
    if os.path.exists(results_path):
        pass
    else:
        try:
            os.makedirs(results_path)
        except:
            # in case another machine created the path meanwhile !:(
            pass



    with parallel_backend('threading', n_jobs= 100):
        #Run The Logistic Regression (LR) module
        #LR_module.LR(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, C=10)

        #Run The Support Vector Machine (SVM) Module
        #SVM_module.SVM(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, C=10)

        #Run The Random Forest (RF) Module
        #RF_module.RF(results_path, Dataset_name, Dataset, Labels, nb_folds= n_folds, n_trees=500)

        #Run The Naive Bayes (NB) Module



    




 The dataset shape is:(185520, 200, 1)

 The number of data samples (N) is:185520

 The number of TS length (T) is:200

 The number of TS dimention (M) is:1
0.49708926261319536
0.49745238422887417
[[4179    3 3508]
 [1188 7645 5336]
 [2490 6135 6620]]
              precision    recall  f1-score   support

         0.0       0.53      0.54      0.54      7690
         1.0       0.55      0.54      0.55     14169
         2.0       0.43      0.43      0.43     15245

    accuracy                           0.50     37104
   macro avg       0.50      0.51      0.51     37104
weighted avg       0.50      0.50      0.50     37104

 fold 1 is Finished!
0.49921841310909876
0.49903065596506474
[[4352    5 3412]
 [1213 7490 5216]
 [2462 6273 6681]]
              precision    recall  f1-score   support

         0.0       0.54      0.56      0.55      7769
         1.0       0.54      0.54      0.54     13919
         2.0       0.44      0.43      0.43     15416

    accuracy                    

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9273031514362741
0.9271338815755178
[[3734   23   23   22    5   18   11   16   16   23   17   23]
 [  37  544    0    9    0   23    0    3    1    0    5   17]
 [  29    0  665    0    2    0    0    0    0    0    0    0]
 [  45   11    0  555    0    3    0    1    0    0   17   11]
 [   8    0    0    0  609    0    0    2    1    0    0    0]
 [   6   31    0    5    0  534    0    0    0    1    2    6]
 [  19    0    0    1    0    0  594    0    0    1    0    0]
 [  19    0    0    2    0    0    0  590   14    1    0    0]
 [  30    0    0    0    0    0    0   16  554    0    2    6]
 [  20    1    0    0    0    2    0    2    2  568    2    0]
 [  44    9    0    4    0    1    0    0    4    1  439   25]
 [  38   10    0    5    0    7    0    1    0    0   20  589]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      3931
           1       0.86      0.85      0.86       639
           2       0.97      0.96      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9246072324997676
0.9244117754235601
[[3693   14   25   22   12   32   22   12   24   19   14   21]
 [  44  609    0    4    0   21    0    1    2    0    7   18]
 [  27    0  659    0    0    0    0    0    0    0    0    0]
 [  43    5    0  541    0    1    0    2    1    0   11    5]
 [   3    0    0    0  551    0    0    1    2    0    0    0]
 [  13   33    0    6    0  537    0    0    0    0    1   13]
 [  15    0    0    0    0    0  581    0    0    1    0    0]
 [  18    1    0    3    0    0    0  595   15    0    0    0]
 [  36    2    0    2    0    1    0   19  541    2    2    3]
 [  29    1    0    0    0    3    1    2    0  573    4    3]
 [  44   13    0    9    0    1    0    1    2    0  504   21]
 [  38    8    0    4    0    9    0    1    3    0   13  562]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      3910
           1       0.89      0.86      0.88       706
           2       0.96      0.96      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9290694431532955
0.928754084290745
[[3714   19   22   23    9   20   21   13   23   10   17   20]
 [  36  526    0    6    0   25    0    6    3    1   10   12]
 [  20    0  680    0    0    0    0    0    0    0    0    0]
 [  53   11    0  534    2    0    0    2    5    0   12    5]
 [   5    0    0    0  627    0    0    2    0    1    0    0]
 [   5   22    0    4    0  575    0    0    0    2    1    7]
 [  15    0    0    1    0    0  605    0    0    1    0    0]
 [  22    1    0    1    0    0    0  590   16    0    0    0]
 [  31    0    0    3    0    1    0   23  570    3    2    0]
 [  19    0    0    1    0    4    0    2    1  627    1    0]
 [  43   10    0    1    0    2    0    1    0    0  432   28]
 [  36   12    0    6    0    3    0    0    2    1   15  514]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      3911
           1       0.88      0.84      0.86       625
           2       0.97      0.97      0.97

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9263735242167891
0.9261886648861651
[[3675   18   23   37    3   33   24   10   30   20   17   19]
 [  36  513    0    8    0   26    0    1    1    1    8   14]
 [  24    0  700    0    1    0    0    0    0    1    0    0]
 [  27    6    0  558    0    1    0    0    3    0   13    5]
 [   5    0    0    0  619    0    0    0    0    0    0    2]
 [   5   22    0    3    0  549    0    0    2    3    2   10]
 [   9    0    0    0    1    0  579    0    0    0    0    0]
 [  17    0    0    2    0    0    0  564   17    1    0    0]
 [  31    0    0    2    0    1    0   25  592    2    5    3]
 [  19    0    0    2    1    3    0    2    1  588    1    2]
 [  43   10    0    4    0    2    0    1    1    0  429   20]
 [  45   15    0    8    0    6    0    0    3    1   22  599]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.94      3909
           1       0.88      0.84      0.86       608
           2       0.97      0.96      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9249790833875616
0.924901458039261
[[3655   26   23   34    5   27   21   27   23   24   24   30]
 [  32  515    0    4    0   28    0    0    1    0    6   19]
 [  19    0  665    0    0    0    0    0    0    0    0    0]
 [  40    7    0  513    0    1    0    2    2    0   11    5]
 [   6    0    0    0  651    0    0    2    0    2    0    2]
 [   7   33    0    6    0  616    0    0    0    3    2    7]
 [  12    0    0    0    0    0  623    0    0    0    0    0]
 [  12    0    0    2    0    0    0  644    7    0    0    0]
 [  36    1    0    0    0    1    0   20  546    1    1    3]
 [  17    0    0    3    0    2    1    3    1  540    2    1]
 [  41   13    0    6    0    2    0    2    3    0  453   22]
 [  30   17    0    2    0    5    0    1    3    0   23  529]]
              precision    recall  f1-score   support

           0       0.94      0.93      0.93      3919
           1       0.84      0.85      0.85       605
           2       0.97      0.97      0.97

0.9814074556103003
0.9813214552250368
[[3838    1    2    1    0    0    8    1    0    0    0    1]
 [  15  587    0    1    0   22    0    0    0    0    3   16]
 [   7    0  692    0    0    0    0    0    0    0    0    0]
 [   2    0    0  632    0    0    0    0    1    0    2    1]
 [   0    0    0    0  636    0    0    0    0    0    0    0]
 [   0   28    0    1    0  584    0    0    0    0    0    5]
 [   1    0    0    0    0    0  644    0    0    0    0    0]
 [  15    0    0    0    0    0    0  597   12    0    0    0]
 [   0    1    0    0    0    0    0    9  633    0    0    0]
 [   1    0    0    0    0    0    0    0    0  567    0    0]
 [   6    1    0    0    0    0    0    0    0    0  518   12]
 [  15    3    0    0    0    3    0    0    2    0    1  629]]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3852
           1       0.95      0.91      0.93       644
           2       1.00      0.99      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.924886120665613
0.9245193448010042
[[3716   13   20   20   10   30   10   12   24   23   23   14]
 [  32  572    0   12    0   29    0    4    3    1    5   25]
 [  21    0  677    0    0    0    0    0    0    0    0    0]
 [  43    7    0  512    1    1    1    0    1    0    8   10]
 [   2    0    0    0  634    0    0    1    0    1    0    1]
 [   6   21    0    4    0  547    0    0    1    1    1    3]
 [  19    0    0    1    1    0  640    0    0    1    0    0]
 [  15    0    0    3    0    0    0  566   14    1    0    0]
 [  33    0    0    1    0    0    0   16  534    2    2    6]
 [  27    1    0    3    0    4    0    2    2  561    2    1]
 [  48   15    0    5    0    2    0    2    4    1  446   26]
 [  45   13    0    4    0    9    0    1    3    1   27  544]]
              precision    recall  f1-score   support

           0       0.93      0.95      0.94      3915
           1       0.89      0.84      0.86       683
           2       0.97      0.97      0.97

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9238635307241796
0.9237285202687991
[[3728   18   37   28    0   34   23   16   28   16   25   25]
 [  43  504    0    2    0   26    0    2    0    0    9   13]
 [  22    0  666    0    2    0    0    0    0    0    0    0]
 [  45   10    0  525    1    0    0    3    1    0   23    8]
 [   8    0    0    0  583    0    0    2    0    0    0    1]
 [   5   34    0    5    0  577    0    0    0    0    2   18]
 [  15    0    0    0    0    0  592    1    0    0    0    0]
 [  16    0    0    2    0    0    0  639   14    0    1    0]
 [  24    1    0    1    0    0    0   15  557    2    5    4]
 [  10    0    0    1    0    1    0    0    0  595    0    1]
 [  43    4    0    4    0    0    0    1    1    0  439   28]
 [  45   15    0    5    0    6    0    1    1    0   16  533]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.93      3978
           1       0.86      0.84      0.85       599
           2       0.95      0.97      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9277679650460166
0.9276967964759397
[[3705   21   20   35   10   25    9   22   27    9   21   28]
 [  33  555    0    5    0   18    0    2    2    0    9   10]
 [  24    0  659    0    1    0    0    0    0    1    0    0]
 [  46    9    0  546    0    3    0    3    2    0   10    5]
 [   4    0    0    0  597    0    0    1    1    0    0    1]
 [   5   29    0    6    0  558    0    0    0    2    2    8]
 [  12    0    0    0    0    0  590    0    0    0    0    0]
 [   6    2    0    1    0    0    0  597   19    0    0    0]
 [  38    2    0    2    0    2    0   18  578    0    3    1]
 [  23    0    0    1    2    3    4    0    2  578    1    1]
 [  36   12    0    7    0    2    0    1    5    0  469   29]
 [  29   18    0    3    0    4    0    1    4    1   13  548]]
              precision    recall  f1-score   support

           0       0.94      0.94      0.94      3932
           1       0.86      0.88      0.87       634
           2       0.97      0.96      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9234916798363856
0.9232633420066033
[[3672   12   16   29    7   27   30   14   22   26   17   26]
 [  37  531    0    9    0   34    0    2    1    1    6   13]
 [  37    0  678    0    1    0    0    0    0    0    0    0]
 [  49    7    0  547    0    3    0    2    5    0    9    6]
 [   4    0    0    0  624    0    0    4    0    1    0    0]
 [  10   26    0    3    0  550    0    1    1    3    4   10]
 [  15    0    0    0    0    0  544    0    0    0    0    0]
 [  19    1    0    1    0    0    0  622   13    0    0    0]
 [  34    1    0    1    0    1    0   22  562    0    2    3]
 [  21    1    0    2    0    0    0    0    1  590    3    1]
 [  42   12    0    6    0    4    0    0    1    0  445   24]
 [  34    9    0    3    0    5    0    1    3    0   22  569]]
              precision    recall  f1-score   support

           0       0.92      0.94      0.93      3898
           1       0.89      0.84      0.86       634
           2       0.98      0.95      0.9

/usr/lib/python3/dist-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.930277958538626
0.9300868632525112
[[3641   26   24   28    9   19   22   15   19   26   15   13]
 [  39  538    0    5    0   26    0    1    2    0    7   15]
 [  13    0  690    0    0    0    0    0    0    0    0    0]
 [  32    8    0  556    0    1    0    1    4    1   10    5]
 [   2    0    0    0  625    0    0    0    2    1    0    1]
 [  12   31    0    5    0  573    0    0    1    1    1    7]
 [  17    0    0    0    0    0  609    0    0    1    0    0]
 [  20    1    0    2    0    0    0  569    9    1    0    0]
 [  25    0    0    3    0    1    0   19  593    2    0    3]
 [  21    0    0    2    0    1    0    5    0  580    2    1]
 [  45   12    0    2    0    0    0    1    0    0  449   18]
 [  35   15    0    9    0    5    0    1    1    1   19  584]]
              precision    recall  f1-score   support

           0       0.93      0.94      0.94      3857
           1       0.85      0.85      0.85       633
           2       0.97      0.98      0.97

0.9847541136004462
0.9846580546495426
[[3979    0    5    0    0    0    3    0    0    0    0    0]
 [  15  538    0    0    0   27    0    0    0    0    0   15]
 [   3    0  711    0    0    0    0    0    0    0    0    0]
 [   2    0    0  606    0    0    0    0    0    0    0    0]
 [   0    0    0    0  603    0    0    0    0    0    0    0]
 [   1   30    0    5    0  595    0    0    0    0    0    6]
 [   3    0    0    0    0    0  590    0    0    0    0    0]
 [   3    0    0    0    0    0    0  614   10    0    0    0]
 [   0    0    0    0    0    0    0    8  588    0    0    0]
 [   0    0    0    0    0    0    0    0    0  628    0    0]
 [   3    0    0    1    0    0    0    0    0    0  514   13]
 [   4    2    0    0    0    0    0    0    0    0    5  627]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99      3987
           1       0.94      0.90      0.92       595
           2       0.99      1.00      0.9